### ISSUE TITLE
Browserify nicht verwendet

### ISSUE THREAD

**Issue by Escaflownevan** [Johannes-Schiel/basic-dev-environment#9]
Browserify in gulpfile.js wird zwar importiert aber nicht verwendet. 

Im Video ists mit drinen ;)

**Comment by Johannes-Schiel** [comment]
Das wurde grade auch von mir Entfernt (2f6dedbd), weil es nicht mehr "sicher" ist und npm Audit leider Critical Issues erzeugte.
